### ISSUE TITLE
How to get fixed AOA and avoid non-convergence

### ISSUE THREAD

**Issue by j2l** [UweSchuster/Aeolus-AeroSketchPad#4] opened 2022-04-24 17:58 UTC
Hello,
I'm learning Aeolus basic functions and validate simple profiles with Xfoil, Javafoil and Nasa FoilSim website https://www.grc.nasa.gov/WWW/K-12/airplane/foil3.html :
An ellipse 20% thickness with a 2.5m span and a 0.1m chord @ 3.94444 m/s.

FoilSim (2D-3D), Xfoil (2D) and Javafoil (2D) roughly get the same result for Cl and Cd:
![image](https://user-images.githubusercontent.com/65325/164988758-cfde1362-737e-4d82-991b-02201c5f4f09.png)
![image](https://user-images.githubusercontent.com/65325/164988773-446afe7f-35d9-46b3-b590-45adebf42b92.png)
![image](https://user-images.githubusercontent.com/65325/164989650-a27b4429-5852-4443-8ebd-5b6cbde292cc.png)

Entered Reynolds number is from Aeolus (freshwater).
I imported the same profile in Aeolus (first time with a 110 points profile, and the second one with a 48 points profile)

First, I can't tell Aeolus to stick to AoA 6.3: Despite choosing AoA1, 2 and 3 as 6.3, it keeps returning a resulting AoA of 9.997°
Even with default -3,5,10° it doesn't get the right AoA around 6.3° but sticks to 9.997°
There's a warning saying it has bad convergence despite smoothing discretization, both with 111 and 48 points.
I find it pretty slower than for other profiles (10 cores result in 25s) even for a simple 48 points dat profile.

How to only compute one AoA?
Any idea why it's not converging and slower than usual? Maybe it's related?
Do you have hints to validate this kind of profile?

I attach my Aeolus file and both ellipses dat files
[ellipses.zip](https://github.com/AeolusAero/Aeolus-AeroSketchPad/files/8550224/ellipses.zip)

Thank you very much and have a great week.

Phil

**Comment by UweSchuster** [comment] 2022-04-26 16:09
Hi Phil,
  

  
Thank you for your message. I am currently travelling and have no access to a computer but here are some notes to help: Aeolus does compute the AOA to provide the target design lift. The 3x AOA you can enter are just the support points for the interpolation. In the Cl,Cd results table you will however find the cl cd values for these support AOAs as well as for the final AOA. For discretization, i propose at least 48 panels in the circumferential direction and an aspect ratio of at least 0.3 for all strips. Hope this helps!
  

  
Best regards,
  
Uwe
  
  
  
  
  
  
  

  
  
>

**Comment by j2l** [comment] 2022-04-27 12:55
Thank you very much for replying despite you're traveling!

Here's what I have in the attached file above (BTW, xml extension is not added to saved file by default):
![image](https://user-images.githubusercontent.com/65325/165516671-6e6a0d9e-cefd-46b2-8a77-61cda74fb744.png)
Aspect ratio is far beyond 0.3

For AoA, if I keep default settings:
![image](https://user-images.githubusercontent.com/65325/165518369-6f12b0f7-1bfd-432b-a4cc-b2e6488f1aa1.png)

Computation and "best" AoA is wrong:
![image](https://user-images.githubusercontent.com/65325/165518602-5aa13cce-303a-4636-91db-b6017203f9b7.png)

as it throws wrong results:
![image](https://user-images.githubusercontent.com/65325/165518885-11162f28-2ad3-4bb8-8f8f-74a1b056610b.png)

I agree with this message:
![image](https://user-images.githubusercontent.com/65325/165519467-9a57ec56-11f9-4050-a071-167ccf9924bc.png)

but I don't know how to improve it. Discretization seems fine.

When you have time, if you can test with my attached files so I can fix the missing thing to correctly do tests, thank you :)
[foil_ellipse_eau.xml.zip](https://github.com/AeolusAero/Aeolus-AeroSketchPad/files/8840327/foil_ellipse_eau.xml.zip)

**Comment by j2l** [comment] 2022-05-22 05:50
bump :smiling_face_with_tear:

**Comment by j2l** [comment] 2022-06-05 14:41
> When you have time, if you can test with my attached files so I can fix the missing thing to correctly do tests, thank you :)

Any news?

**Comment by UweSchuster** [comment] 2022-06-05 17:38
I am currently busy and will not be able to look into it before August
  
  
  
  
  
  
  

  
  
>

**Comment by j2l** [comment] 2022-06-05 17:59
I understand.
I'll wait until August.

**Comment by UweSchuster** [comment] 2022-07-25 17:48
Hi Phil!

Sorry for the long waiting time. I am now reviewing your files and can reproduce the issue. First, I tweaked your airfoil files by adding the last [1.0 0.0] point to make sure the trailing edge is closed and the airfoil is imported properly.

I think it is because of the Airfoil itself and not the discretization. Changing to NACA0012 works. Today, AeolusASP is based on potential flow which requires airfoils with sharp trailing edges (to apply the Kutta condition). The elliptical airfoil is therefore inherently challenging for potential flow solvers.

**Comment by UweSchuster** [comment] 2022-07-25 18:00
Here is a working example, which is not so far off though:
[Ellipse_Test.zip](https://github.com/AeolusAero/Aeolus-AeroSketchPad/files/9183723/Ellipse_Test.zip)

reading approximately Cl = 0.74 at 6.3 deg.

![image](https://user-images.githubusercontent.com/47351070/180843630-883a3d69-e93e-4fae-8ffa-5c0aab2d200b.png)

**Comment by j2l** [comment] 2022-07-26 14:37
Thank you @UweSchuster 
Indeed, I had the same issue (Kutta condition) with another solver, so it makes more sense to me now :smile: 
Looks like your file was done with 4.22 and latest downloadable version is 4.21.

**Comment by UweSchuster** [comment] 2022-09-24 14:34
To summarize here:
- Blunt TE airfoils - wont fix for now as this is beyond potential flow
- solve for a given AOA instead of solve AOA for a given lift -> new Issue #13

**Closed as completed by UweSchuster** 2022-09-24 14:34 UTC
